

eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
spring.application.name=Hotel-Service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

